### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation`

### ISSUE THREAD

**Issue by kevinbsc** [diging/tethne#153]
I am running on Windows 10 and getting the error below:

`ImportError                               Traceback (most recent call last)
<ipython-input-21-80dbe9e6810e> in <module>()
      1 import nltk
----> 2 from tethne.readers import zotero
      3 #from pdfminer.pdfdocument import PDFDocument
      4 import matplotlib.pyplot as plt
      5 from nltk.corpus import stopwords

c:\anaconda\lib\site-packages\tethne\readers\zotero.py in <module>()
      5 import nltk
      6 import codecs
----> 7 import magic    # To detect file mime-type.
      8 import slate    # PDF processing.
      9 import chardet  # Detect character encodings.

c:\anaconda\lib\site-packages\magic.py in <module>()
    159 if not libmagic or not libmagic._name:
    160     # It is better to raise an ImportError since we are importing magic module
--> 161     raise ImportError('failed to find libmagic.  Check your installation')
    162 
    163 magic_t = ctypes.c_void_p

ImportError: failed to find libmagic.  Check your installation`

**Comment by erickpeirson** [comment]
Hey @kevinbsc; unfortunately we don't have the personnel to support a Windows version right now. 

That being said, it looks like the missing dependency (libmagic) is used by packages that we use in the next minor version. I've added [TETHNE-127](https://diging.atlassian.net/browse/TETHNE-127) to address this.
