### ISSUE TITLE
Error when using  tethne.writers.corpora.to_documents()

### ISSUE THREAD

**Issue by srelliorm** [diging/tethne#19]
I'm using tethne to work with JSTOR DfR data. I'm using tethne to explicitly correlate wordcounts with DOIs. Working from the command line, when I correlated the wordcounts with the DOIs, I needed to export the information in a file, which I could then use in Mallet. 

Problem: When I used the command: >>> wr.corpora.to_documents('./mycorpu1s', wordcounts),

 I received the following error message: Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Applications/anaconda/lib/python2.7/site-packages/tethne/writers/corpora.py", line 36, in to_documents
    for i in xrange(freq) ]) + '\n')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u03c6' in position 17799: ordinal not in range(128)

**Comment by erickpeirson** [comment]
@srelliorm : this should fix it. Give another try (be sure to uninstall and reinstall), and reopen this ticket if you still have trouble.
