### ISSUE TITLE
During download unable to find version 0.6.0-beta

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#24]
Python 2.7 installed, tethne 0.6.0-beta downloaded and unzipped, when installing from terminal I receive this error
![screen shot 2014-08-04 at 4 37 58 pm](https://cloud.githubusercontent.com/assets/8186095/3805145/7e168ce2-1c31-11e4-9075-0109e8939908.png)
![screen shot 2014-08-04 at 4 48 32 pm](https://cloud.githubusercontent.com/assets/8186095/3805160/dd84f3e4-1c31-11e4-9f82-5ededc4bd53a.png)

**Comment by erickpeirson** [comment]
Hi Ken, thanks for this. Try specifying the version explicitly:

`$ pip install tethne==0.6.0-beta`

But this should definitely get fixed for the next release.

**Comment by kaiello** [comment]
Erick,

No problem.

Specifying the version worked. FYI there was the same bug in Tethne
0.5.0-dev.

Ken

**Comment by erickpeirson** [comment]
Glad it worked! I'll keep this open so I remember to fix it.

**Comment by erickpeirson** [comment]
Looks like the reason for this is that `pip` ignores pre-release versions by default (see [this page](http://pip.readthedocs.org/en/latest/reference/pip_install.html#pre-release-versions)). So until we drop the `-beta` tag (which is probably not compliant anyway), use the `--pre` flag. e.g.:

```
$ pip install tethne --pre
```

I'll update the documentation to reflect this.
