### ISSUE TITLE
ImportError: No module named corpus

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#26]
When trying to create a corpus from using the command line:

$ >>>from tethne.readers import dfr

the following error occurs

![screen shot 2014-08-08 at 1 22 28 pm](https://cloud.githubusercontent.com/assets/8186095/3862403/5c45b748-1f3b-11e4-821e-dd011fc3ea36.png)
![screen shot 2014-08-08 at 1 23 25 pm](https://cloud.githubusercontent.com/assets/8186095/3862404/5c4e5e98-1f3b-11e4-98b8-e51491dad4a2.png)

**Comment by erickpeirson** [comment]
Great, thanks; checking the rest of the package to make sure we use relative imports.

**Comment by erickpeirson** [comment]
Ok, should be fixed. Try [this updated release](https://github.com/diging/tethne/releases/tag/v0.6.1-beta%28patched%29), or uninstall/reinstall from PyPi (`pip install tethne --pre`). Let me know how it goes.
