### ISSUE TITLE
Syntax Error: EOL while scanning string literal

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#27]
After opening Python from command line and then while trying to import corpus 

![screen shot 2014-08-08 at 3 17 04 pm](https://cloud.githubusercontent.com/assets/8186095/3863498/d4c303ca-1f49-11e4-99d4-af2b9f056480.png)

**Comment by erickpeirson** [comment]
Hi Ken,

It looks like you are using mismatched quotation marks. If you look where the carat `^` is pointing, you've paired a double-quote `"` with a single-quote `'`.

```
MyCorpus = Corpus(papers, features={'wc':wordcounts}, index_by='doi")
```

Did you enter this by hand, or copy/paste from a tutorial? If the latter, let me know so I can fix the typo.

**Comment by kaiello** [comment]
Erick,

From the tutorial 
![screen shot 2014-08-08 at 3 28 02 pm](https://cloud.githubusercontent.com/assets/8186095/3863597/52fe686e-1f4b-11e4-8c4b-5ee83156cf1b.png)

**Comment by erickpeirson** [comment]
Ok, I don't see the typo in the tutorial. See how single-quotes are paired with single-quotes? Check out  the section on strings in [this tutorial](http://en.wikibooks.org/wiki/Python_Programming/Variables_and_Strings).

**Comment by kaiello** [comment]
My fault, no typo.
