### ISSUE TITLE
ParseError when using dfr.read_corpus

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#28]
![image](https://cloud.githubusercontent.com/assets/8186095/3909026/85b3325a-2309-11e4-811d-c0bb8fbd7bc2.png)

`<abstract>Background. We hypothesized that the inflammatory response in the lungs of children with cystic fibrosis (CF) would vary with the type of infecting organism, being greatest with Pseudomonas aeruginosa and Staphylococcus aureus. Methods. A microbiological surveillance program based on annual bronchoalveolar lavage (BAL) collected fluid for culture and assessment of inflammation was conducted. Primary analyses compared inflammation in samples that grew a single organism with uninfected samples in cross-sectional and longitudinal analyses.                Results. Results were available for 653 samples from 215 children with CF aged 24 days to 7 years. A single agent was associated with pulmonary infection (≥10               5               cfu/mL) in 67 BAL samples, with P. aeruginosa (n = 25), S. aureus (n = 17), and Aspergillus species (n = 19) being the most common. These microorganisms were associated with increased levels of inflammation, with P. aeruginosa being the most proinflammatory. Mixed oral flora (MOF) alone was isolated from 165 BAL samples from 112 patients, with 97 of these samples having a bacterial density ≥10               5               cfu/mL, and was associated with increased pulmonary inflammation (P <.001). For patients with current, but not past, infections there was an association with a greater inflammatory response, compared with those who were never infected (P <.05). However, previous infection with S. aureus was associated with a greater inflammatory response in subsequent BAL.              Conclusions. Pulmonary infection with P. aeruginosa, S. aureus, or Aspergillus species and growth of MOF was associated with significant inflammatory responses in young children with CF. Our data support the use of specific surveillance and eradication programs for these organisms. The inflammatory response to MOF requires additional investigation.</abstract>`

**Comment by erickpeirson** [comment]
The more I think about this, the clearer it is to me that we should not attempt to accommodate invalid XML. Let's work with the JSTOR folks to correct this on their end.

I'll leave this issue open to track developments on that front.

**Comment by erickpeirson** [comment]
This should now be fixed! JSTOR applied a patch, and I created a new request for the microbiome dataset; all of the special characters are now encoded properly.

**Comment by kaiello** [comment]
I will DL and try later today.

Ken

On Tue, Aug 19, 2014 at 11:31 AM, Erick notifications@github.com wrote:

> Closed #28 https://github.com/diging/tethne/issues/28.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/diging/tethne/issues/28#event-154622530.

## 

Kenneth D. Aiello
Arizona State University
Center for Biology & Society
PO Box 874601
Tempe, AZ 85287- 4601
