### ISSUE TITLE
TypeError Traceback fig = C.plot_distribution('jtitle') """using wos data"""

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#29]
![screen shot 2014-08-13 at 11 46 45 am](https://cloud.githubusercontent.com/assets/8186095/3910719/939a0a2c-231a-11e4-8f50-2a2ed29f596d.png)

![screen shot 2014-08-13 at 11 50 09 am](https://cloud.githubusercontent.com/assets/8186095/3910740/b4dfc8fc-231a-11e4-9b0d-041046506d1d.png)

'\n--------------------------------------------------------------------------\nTypeError                                 Traceback (most recent call last)\n<ipython-input-35-bb7a71ad7a35> in <module>()\n----> 1 fig = C.plot_distribution(\'jtitle\')\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/tethne/classes/corpus.pyc in plot_distribution(self, x_axis, y_axis, type, aspect, step, fig, mode, fkwargs, *_kwargs)\n   1509                 yvals = self.feature_distribution(featureset, feature, x_axis,\n   1510                                                   mode=fmode, normed=fnormed)\n-> 1511             plt.**dict**[type](xkeys, yvals, **kwargs)\n   1512             plt.xlim(xkeys[0], xkeys[-1])   # Already sorted.\n   1513         else:\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.pyc in bar(left, height, width, bottom, hold, *_kwargs)\n   2513         ax.hold(hold)\n   2514     try:\n-> 2515         ret = ax.bar(left, height, width=width, bottom=bottom, *_kwargs)\n   2516         draw_if_interactive()\n   2517     finally:\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/axes.pyc in bar(self, left, height, width, bottom, *_kwargs)\n   5051             r.get_path()._interpolation_steps = 100\n   5052             #print r.get_label(), label, \'label\' in kwargs\n-> 5053             self.add_patch(r)\n   5054             patches.append(r)\n   5055 \n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/axes.pyc in add_patch(self, p)\n   1560         if p.get_clip_path() is None:\n   1561             p.set_clip_path(self.patch)\n-> 1562         self._update_patch_limits(p)\n   1563         self.patches.append(p)\n   1564         p._remove_method = lambda h: self.patches.remove(h)\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/axes.pyc in _update_patch_limits(self, patch)\n   1578         vertices = patch.get_path().vertices\n   1579         if vertices.size > 0:\n-> 1580             xys = patch.get_patch_transform().transform(vertices)\n   1581             if patch.get_data_transform() != self.transData:\n   1582                 patch_to_data = (patch.get_data_transform() -\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/patches.pyc in get_patch_transform(self)\n    574 \n    575     def get_patch_transform(self):\n--> 576         self._update_patch_transform()\n    577         return self._rect_transform\n    578 \n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/patches.pyc in _update_patch_transform(self)\n    567         width = self.convert_xunits(self._width)\n    568         height = self.convert_yunits(self._height)\n--> 569         bbox = transforms.Bbox.from_bounds(x, y, width, height)\n    570         rot_trans = transforms.Affine2D()\n    571         rot_trans.rotate_deg_around(x, y, self._angle)\n\n/Users/Kenneth/anaconda/lib/python2.7/site-packages/matplotlib/transforms.pyc in from_bounds(x0, y0, width, height)\n    819         _width_ and _height_ may be negative.\n    820         """\n--> 821         return Bbox.from_extents(x0, y0, x0 + width, y0 + height)\n    822 \n    823     @staticmethod\n\nTypeError: cannot concatenate \'str\' and \'float\' objects\n'

**Comment by erickpeirson** [comment]
I'm a bit confused by the two screenshots. Which error is this issue about?

**Comment by erickpeirson** [comment]
Nevermind, I see now. Looks like the second screenshot is unrelated.
