### ISSUE TITLE
AttributeError: 'module' object has no attribute 'corpus_from_dir'

### ISSUE THREAD

**Issue by deryc** [diging/tethne#38]
Following the tutorial, I am running into problems with wos.corpus_from_dir(datapath).

The error message is as follows:

Traceback (most recent call last):
  File "/Users/derycpainter/Desktop/WILLIAMS_57_networks/basic_coCitation", line 4, in <module>
    MyCorpus = wos.corpus_from_dir('datapath')
AttributeError: 'module' object has no attribute 'corpus_from_dir'

Here's a link to the page:  http://bit.ly/1AwiZU9

Perhaps the module was renamed?

**Comment by erickpeirson** [comment]
Hi Deryc, can you post your code here?

**Comment by deryc** [comment]
How do I get one of those fancy code window things?

```
datapath = '/Users/derycpainter/Desktop/WILLIAMS_57_networks/williams57_downloadedrecords_all.txt'

from tethne.readers import wos
MyCorpus = wos.corpus_from_dir(datapath)

MyCorpus.slice('date','time period',window_size=2)

from tethne import GraphCollection
kw = {'threshold':2,'topn':200}
G = GraphCollection().build(MyCorpus, 'date','papers','cocitation',method_kwargs=kw)

from tethne.writers import collection
collection.to_dxgmml(G,'~/cocitation.xgmml')
```

**Comment by deryc** [comment]
ugh...sorry...just realized that's for multiple files

that's probably the issue

**Comment by erickpeirson** [comment]
Well, that should give a different error. Can you type this into the terminal, and paste the output here?

`pip freeze | grep tethne`

Check out [this page](https://guides.github.com/features/mastering-markdown/) to learn about Markdown (fancy code window things are blockquotes).

**Comment by deryc** [comment]
tethne==0.6.1-beta

**Comment by erickpeirson** [comment]
Hmmm...OK. Well, you probably want 0.6.2-beta, but I'm not convinced that's the problem. Better try it anyway. I'd completely uninstall and reinstall...

```
pip uninstall tethne
pip install tethne --pre
```

Then try it again.

**Comment by deryc** [comment]
output reads tethne==0.6.2-beta

also, changed wos.read(datapath)

now, this:

![screen shot 2014-08-19 at 4 48 07 pm](https://cloud.githubusercontent.com/assets/4674561/3974833/512076dc-27fb-11e4-9fc6-f32098a9ffc9.png)

**Comment by erickpeirson** [comment]
Ok, so the bug was related to #26, which was fixed in 0.6.2-beta. So that's good.

The error you're getting now is because you're trying to `slice` a list. `wos.read` returns a list of `Paper` instances, not a `Corpus`. I think that you want `wos.read_corpus`.

**Comment by deryc** [comment]
:(

![screen shot 2014-08-19 at 4 55 00 pm](https://cloud.githubusercontent.com/assets/4674561/3974879/4d549cf8-27fc-11e4-8fa9-068604fbe93a.png)

**Comment by erickpeirson** [comment]
Open a new terminal window, and start the Python interpreter. Then do this:

```
>>> from tethne.readers import wos
>>> wos.__dict__.keys()
```

**Comment by deryc** [comment]
output reads

['_handle_author_institutions', '_validate', '_new_wos_dict', 'parse', 'subdict', '__name__', 'Corpus', '_parse_cr', '_create_ainstid', 'uuid', 'Dictionary', 'contains', 'corpus_from_dir', 'overlap', '__package__', 'concat_list', 're', 'strip_punctuation', 'swap', '_create_ayjid', '__doc__', 'DataError', 'string', 'attribs_to_string', '**builtins**', '**file**', '_handle_authors', 'read_corpus', 'dict_from_node', 'ET', 'copy', 'from_dir', '_new_query_dict', '_wos2paper_map', 'convert', 'read', 'Paper', 'strip_non_ascii', 'os']

**Comment by deryc** [comment]
well, there's the file right there....

**Comment by erickpeirson** [comment]
In that same Python session, try this:

```
>>> wos.read_corpus
```

(note that there are no parentheses)

**Comment by deryc** [comment]
here's what I get

function read_corpus at 0x1071aaf50

**Comment by erickpeirson** [comment]
Ok. And how are you running your script (the code you posted)?

**Comment by deryc** [comment]
from idle > run

**Comment by erickpeirson** [comment]
You're using the wrong IDLE. If you installed Anaconda Python, then you're probably using the Anaconda pip when you install tethne. But if you're starting IDLE from a desktop/launchpad icon, you're probably starting the IDLE that part of the built-in Python installation for OSX. 

Try running your script from the terminal.

```
$ python yourscript.py
```

Better yet, I recommend using an iPython notebook. From the terminal, do...

```
$ ipython notebook --pylab=inline
```

**Comment by deryc** [comment]
from iPython

![screen shot 2014-08-19 at 5 20 26 pm](https://cloud.githubusercontent.com/assets/4674561/3975075/bf260e80-2800-11e4-826c-1d1e4d4dcb6a.png)

**Comment by erickpeirson** [comment]
Should be `time_period` (note the underscore)

**Comment by deryc** [comment]
the file it spit out was a bit off

all it says:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
graph
/graph

**Comment by deryc** [comment]
current code looks like:

datapath = '/Users/derycpainter/Desktop/WILLIAMS_57_networks/williams57_downloadedrecords_all.txt'

from tethne.readers import wos
MyCorpus = wos.read_corpus(datapath)

MyCorpus.slice('date','time_period',window_size=2)

from tethne import GraphCollection
kw = {'threshold':2,'topn':200}
G = GraphCollection().build(MyCorpus, 'date','papers','cocitation',method_kwargs=kw)

from tethne.writers import collection
collection.to_dxgmml(G,'/Users/derycpainter/Desktop/cocitation.xgmml')

**Comment by erickpeirson** [comment]
How many nodes and edges are in your GraphCollection?

**Comment by deryc** [comment]
![screen shot 2014-08-20 at 10 20 46 am](https://cloud.githubusercontent.com/assets/4674561/3985113/69ed7622-288e-11e4-8b74-ecea321c8c36.png)

**Comment by erickpeirson** [comment]
Ok, those are the numbers of papers and citations in your corpus. But what about the [nodes](http://diging.github.io/tethne/doc/0.6.1-beta/tethne.classes.graphcollection.html#tethne.classes.graphcollection.GraphCollection.nodes) and [edges](http://diging.github.io/tethne/doc/0.6.1-beta/tethne.classes.graphcollection.html#tethne.classes.graphcollection.GraphCollection.edges) in your [GraphCollection](http://diging.github.io/tethne/doc/0.6.1-beta/tethne.classes.graphcollection.html#tethne.classes.graphcollection.GraphCollection) ?

**Comment by deryc** [comment]
![screen shot 2014-08-20 at 10 32 55 am](https://cloud.githubusercontent.com/assets/4674561/3985282/157a5d56-2890-11e4-9d4b-69f4d7190dcb.png)

**Comment by deryc** [comment]
something doesn't add up here....

**Comment by erickpeirson** [comment]
That looks reasonable, but it doesn't tell you how many [nodes](http://diging.github.io/tethne/doc/0.6.1-beta/tethne.classes.graphcollection.html#tethne.classes.graphcollection.GraphCollection.nodes) and [edges](http://diging.github.io/tethne/doc/0.6.1-beta/tethne.classes.graphcollection.html#tethne.classes.graphcollection.GraphCollection.edges) are in your GraphCollection. 

```
>>> print len(G.nodes())
>>> print len(G.edges())
```

**Comment by deryc** [comment]
I must be missing something.  

![screen shot 2014-08-20 at 10 40 40 am](https://cloud.githubusercontent.com/assets/4674561/3985387/3b612292-2891-11e4-9ab9-7357de964a41.png)

**Comment by erickpeirson** [comment]
Try relaxing `threshold` or `topn`. Probably there are not >= 2 co-citations among the top 200 cited references in each slice.

**Comment by deryc** [comment]
still nothing.  bumped up the window size, lowered TH, raised topn.
![screen shot 2014-08-20 at 10 47 58 am](https://cloud.githubusercontent.com/assets/4674561/3985512/486dd614-2892-11e4-9d95-7a5d4a59b36c.png)

![screen shot 2014-08-20 at 10 50 22 am](https://cloud.githubusercontent.com/assets/4674561/3985536/811cb0de-2892-11e4-82ae-97da92c74a86.png)

**Comment by erickpeirson** [comment]
Then raise `topn` more. Remember, you're working with more than 65,000 cited references; . You can use a float instead of an integer to specify a percentile, too. Every dataset is different, so it's going to take some inspection of the data to pick useful values for those arguments. 

If you removed the `topn` parameter entirely, or set it to 0.5, and still got an empty graph then there might be a problem.

**Comment by deryc** [comment]
0.5, 0.99, 0.1, and this all gave the same empty deal
![screen shot 2014-08-20 at 11 02 48 am](https://cloud.githubusercontent.com/assets/4674561/3985695/40704828-2894-11e4-84fb-42bc45ac60de.png)

**Comment by erickpeirson** [comment]
Are you in the office? I'll be in soon and can take a closer look.

**Comment by deryc** [comment]
yep, see ya soon

**Comment by erickpeirson** [comment]
Closing this; opened #39 to deal with build weirdness.
