### ISSUE TITLE
Isolating co-citing papers {Enhancement}

### ISSUE THREAD

**Issue by deryc** [diging/tethne#49]
I would like to be able to take two separate records, isolate the papers that cite both papers, and build networks and analyze just those co-citing documents.

**Comment by erickpeirson** [comment]
Ok; I think that we can generalize this: we need a function that returns a
list of Papers that contain some set of (one or more) features. You could
then use that list of Papers as input to some other network-building
function. Does that sound right?

## 

http://gradinfo.cbs.asu.edu/?page_id=49
NSF Graduate Research Fellow
Center for Biology & Society
School of Life Sciences
Arizona State University

**Comment by erickpeirson** [comment]
Or maybe just a list of Paper ids, since some analyses will again require access to features, which are properties of the Corpus rather than (just) the Papers themselves.

Something like...

```
>>> subset = MyCorpus.papers_containing('featureset', ['feature1', ... 'featureN'])
>>> subset
['doi1', 'doi2', ... 'doiM']
>>> some_analysis_function(MyCorpus, using=subset)
```

**Comment by deryc** [comment]
the ids might work better.  having access to the features attached to the papers would be wonderful. especially when trying to attach other metrics to the papers

**Comment by erickpeirson** [comment]
In v0.7, this is possible using `Corpus`' new `__getitem__` behavior. To select papers that cite `ROBERTS 1985 CELL` you would do:

``` python
>>> corpus['citedReferences', 'ROBERTS 1985 CELL']   # Get a list of papers.
[<tethne.classes.paper.Paper object at 0x103118f90>,
 <tethne.classes.paper.Paper object at 0x103169190>]
```

To get a subcorpus (e.g. to use in a network-building method), use the `subcorpus` class-method. 

``` python
>>> corpus.subcorpus(('citedReferences', 'ROBERTS 1985 CELL'))    # Note the tuple arg.
<tethne.classes.corpus.Corpus object at 0x103169190>]
```
