### ISSUE TITLE
Can't load data in Line 1 in notebook 3. Time and Change 

### ISSUE THREAD

**Issue by yzou20** [diging/tethne#51]
I received an error called ""NoneType" object is not utterable." I have attached a screenshot for your diagnosis. I used the same datadirpath for Notebook 2 and it works fine. Thanks 
![screen shot 2014-10-01 at 4 35 24 pm](https://cloud.githubusercontent.com/assets/8672876/4485104/01ba8420-49c5-11e4-9630-f52bef586ccc.png)

**Comment by erickpeirson** [comment]
Thanks Yawen, I'll look at this right away. In an email, can you send the offending data set?

**Comment by yzou20** [comment]
Here it is, it is very large, so i put it in the Google Drive, hope you can
download it. Thanks!!​
 download.txt
[Edit: link removed]
​

Yawen Zou

PhD Candidate
Center for Biology and Society
Arizona State University
Tel: 001-602-459-4047
Email: yzou20@asu.edu
Office: LSA 269, SoLS complex

**Comment by erickpeirson** [comment]
The problem is at [paper.py line 138](https://github.com/diging/tethne/blob/python/tethne/classes/paper.py#L138), where `Paper.authors()` is  returning `None`.  It should return an empty list, instead.
