### ISSUE TITLE
Author names in citations are formatted inconsistently

### ISSUE THREAD

**Issue by kaiello** [diging/tethne#52]
Author names are formatted as all caps or caps and lower case

![screen shot 2014-10-10 at 11 45 36 am](https://cloud.githubusercontent.com/assets/8186095/4597426/ca34c480-50ad-11e4-941e-197a485c4666.png)

**Comment by erickpeirson** [comment]
See tests in v0.7:
[`test_readers_dfr`](https://github.com/diging/tethne/blob/python/tethne/tests/test_readers_dfr.py#L12)
[`test_readers_wos`](https://github.com/diging/tethne/blob/python/tethne/tests/test_readers_wos.py#L33)
