### ISSUE TITLE
mycorpus_meta.csv file not created

### ISSUE THREAD

**Issue by deryc** [diging/tethne#57]
Working with DfR data, the mycorpus_doc.txt file is created, but the mycorpus_meta.csv is not.

import tethne.readers as rd
datapath = '/Users/derycpainter/Desktop/Research/1-12-15/125_records_williams57'
wordcounts = rd.dfr.ngrams(datapath, N='uni')
import tethne.writers as wr
wr.corpora.to_documents('./mycorpus', wordcounts)

**Comment by deryc** [comment]
![screen shot 2015-01-20 at 10 38 29 am](https://cloud.githubusercontent.com/assets/4674561/5822387/de434950-a090-11e4-83f2-92e7e32f33cb.png)

however, in the notebook, the file shows as being created.

**Comment by erickpeirson** [comment]
`writers.corpora.to_documents` only writes the metadata file if the optional kwarg `metadata` is provided (default is `None`). The documentation is a bit unclear on that point, so I should update it accordingly. Or maybe it should have a non-none default so that it always writes a metadata file...thoughts on what you'd prefer?

**Comment by deryc** [comment]
I think a non-none default would be best.  I mean, when is metadata a bad
thing?

On Tue, Jan 20, 2015 at 12:17 PM, Erick notifications@github.com wrote:

> writers.corpora.to_documents only writes the metadata file if the
> optional kwarg metadata is provided (default is None). The documentation
> is a bit unclear on that point, so I should update it accordingly. Or maybe
> it should have a non-none default so that it always writes a metadata
> file...thoughts on what you'd prefer?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/diging/tethne/issues/57#issuecomment-70714119.

## 

Deryc Painter
Research Assistant
Ph.D Student
School of Life Sciences and the Center for Biology and Society
Arizona State University
Tempe, Arizona 85287-4501

http://devo-evo.lab.asu.edu/?q=dpainter
http://gpse.asu.edu/gpse.asu.edu/GPSE_Mentors.html

**Comment by deryc** [comment]
Current state of things, not sure what to make of it.

![screen shot 2015-01-20 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/4674561/5828051/43a2effe-a0bd-11e4-96b5-c15c3be04964.png)

**Comment by erickpeirson** [comment]
~~See the docstring for to_documents; expects metadata kwarg to be a dict.~~

**Comment by erickpeirson** [comment]
I take that back, not a dict:

```
metadata : tuple
        (`keys`, dict): `keys` is a list of metadata keys, and dict contains
        metadata values dict for each paper. ( [ str ], { str(p) : dict } ) 
```

For an example of `to_documents` in use, check out the [`_generate_corpus` method in `MALLETModelManager`](https://github.com/diging/tethne/blob/python/tethne/model/managers/mallet.py#L138).
