### ISSUE TITLE
Small fixes on SIF attribute files

### ISSUE THREAD

**Issue by erickpeirson** [diging/tethne#6]
Aaron, you may have already done this in your branch? In writers.to_sif():
- The first line in each attribute file should be the name of the attribute,
- For edge attributes, the relationship/predicate should be enclosed in parentheses. 

E.g. if the interaction is:
`Darwin cites Lamarck`

An edge attribute file might look like:

```
date
Darwin (cites) Lamarck = 1859
```

**Comment by aabaker99** [comment]
Erick,

Can you post a link to the SIF format reference? When I wrote the to_sif function I was basing it off of http://wiki.cytoscape.org/Cytoscape_User_Manual/Network_Formats.

I have not yet made any changes.

**Comment by erickpeirson** [comment]
This might help: [http://www.cytoscape.org/manual/Cytoscape2_5Manual.html#Node and Edge Attributes]()

**Comment by aabaker99** [comment]
A temporary fix is in place. Before adding graph attributes as we discussed I wanted those networks' test cases to be up to date. They now are and I'm adding a pull request. Next I will be adding the graph attributes and making the associated additions to the test cases.

**Comment by erickpeirson** [comment]
Excellent.
