### ISSUE TITLE
Error with import isi-wos data in tethne package on python

### ISSUE THREAD

**Issue by faryou** [diging/tethne#61]
![tethne1](https://cloud.githubusercontent.com/assets/10322370/6059156/94171cc0-ad43-11e4-97e7-1bb6e7dabdf3.JPG)

**Comment by erickpeirson** [comment]
Please send along the file that you're trying to parse, so that we can get to the bottom of this exception.

**Comment by faryou** [comment]
tanx a lot.
the file is

On Thu, Feb 5, 2015 at 6:56 PM, Erick notifications@github.com wrote:

> Please send along the file that you're trying to parse, so that we can get
> to the bottom of this exception.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/diging/tethne/issues/61#issuecomment-73064369.

*\* removed WoS data **

**Comment by erickpeirson** [comment]
What procedure are you using to download this file from the Web of Science? It looks like you're getting is a tab-delimited file with field-tag headers, whereas Tethne expects just a plain field-tagged file (what WoS calls "plain text"). Take a look [here](http://diging.github.io/tethne/doc/0.6.1-beta/tutorial.getting_data.html#web-of-science) for details.

**Comment by faryou** [comment]
tanx a lot erick tren.

**Comment by faryou** [comment]
tanx a lot
