### ISSUE TITLE
error=2

### ISSUE THREAD

**Issue by khasseh** [diging/tethne#64]
when I select the file and choose WOS and click on "Read files", I encounter with a message:
Couldn't run script: Cannot run program "python": CreateProcess error=2, The system cannot find the file specified
What does it mean? What shall I do?

**Comment by erickpeirson** [comment]
Hi @khasseh; sounds like you're using the GUI that we put together for a course a few semesters ago, and not the tethne Python library itself. Is that correct?

**Comment by khasseh** [comment]
Hi
Yes, you are right. What shall I do?
در تاریخ ۱۷ مارس ۲۰۱۵ ۲۳:۰۳، "Erick" notifications@github.com نوشت:

**Comment by erickpeirson** [comment]
Sorry for the delay in replying. The GUI is way behind, and probably won't be updated. There are plans for a web application, however; keep an eye on this repo if you're interested.
