### ISSUE TITLE
Problems with LDAModel load

### ISSUE THREAD

**Issue by zarthon** [diging/tethne#65]
I am trying to use tethne to load my LDA model output. My model is created using set of webpages on the internet. I am just playing it around and thankfully I was able to hack my way to make it work.
While loading I  faced couple of problems, 
- I didn't have a metadata file. Is the file really necessary? What if I don't have any meta data with my documents? 
- I got a key lookup error in line 76 tethne/model/corpus/ldamodel.py, In a very hacky way I was able to bypass this. I was just wondering if metadata can be made optional or not?

**Comment by erickpeirson** [comment]
Hi @zarthon ; sorry for the delay in getting back to you. v0.7 is a fairly significant refactor, and there are some big changes to how metadata is handled in the MALLET interface. I'll update this issue with more details in a few days.

**Comment by erickpeirson** [comment]
The API for working with MALLET is much simpler now. Assuming that you have already generated a `Corpus` with some features (unigrams, say), you can fit an LDA model with MALLET using:

``` python
>>> from tethne.model.corpus.mallet import LDAModel    # This will get simpler...
>>> model = LDAModel(corpus, featureset_name='unigrams')
>>> model.fit(Z=200, max_iter=10000)
```

If you want to perform the CL call to MALLET yourself, you can use the `LDAModel` to generate a MALLET-readable corpus...

``` python
>>> model = LDAModel(corpus, featureset_name='unigrams')
>>> model.temp = "/path/to/my/working/directory"    # MALLET input and output files are created here.
>>> model.prep()    # Generates the needed files.
```

...and then read in the results after you fit the LDA model. 

``` python
>>>  model.load()    # Assuming that this is the same LDAModel instance.
```

All metadata resides in the `Corpus` object, so metadata doesn't get passed around as an external file as was the case before.
