### ISSUE TITLE
Problems with Corpus.slice

### ISSUE THREAD

**Issue by Koptyaevas** [diging/tethne#66]
Hi there, 
I'm really new in programming, that's why my question can be probably boring or stupid, sorry for this! I'm trying to build co-authorship graph in Gephi (_graphml format_). Everything is fine, but I don't understand, how to import dates in the same file. My code is following:

```
from tethne.readers import wos
MyCorpus = wos.corpus_from_dir(datapath)
from tethne.networks import authors
ca_graph = authors.coauthors(MyCorpus.all_papers())
from tethne.writers import graph
graph.to_graphml(ca_graph, './file.graphml')
```

So, in this **file.graphml** I have **authors** and **institutions**, but I don't have any **years** (when this work was published). I have found a piece of code [here](http://diging.github.io/tethne/doc/0.6.1-beta/tutorial.coauthors.html#building-a-graphcollection)

```
MyCorpus.slice('date', 'time_period', window_size=1, cumulative=True)
```

but I have no idea, how to write everything in one file. I will appreciate all the help!

**Comment by erickpeirson** [comment]
Hi @Koptyaevas, sorry for the delay in getting back to you about this. Probably the easiest thing would be to pass the `edge_attribs` keyword argument to `coauthors`. For example:

``` python
ca_graph = authors.coauthors(MyCorpus.all_papers(), edge_attribs=['date','ayjid'])
```

That should give you an attribute called `date` on each of your edges. Does that do what you want? If not, tell me more about what the desired behavior is, and we'll try to incorporate that into the next version.

Thanks!

**Comment by erickpeirson** [comment]
Going to close this since there has been no updates in over a year. Please reopen if you're still having trouble with this.
