### ISSUE TITLE
the way wos reader module analyzes the names of the authors of the references

### ISSUE THREAD

**Issue by yzou20** [diging/tethne#89]
For authors whose last name has two characters, the wos reader module breaks the last name into two parts and treats them as first name and last name. For example, for author "van Kampenng NG", the tethne module reads the last name as "van," and the first name as "Kampenng," and ignores the real firstname "NG."

**Comment by nischalsamji** [comment]
Hi Yawen, So Is this the format that you are expecting?

First Name: NG
Last Name: Kampenng

**Comment by erickpeirson** [comment]
This is hard. One thing that you might consider is using a whitelist of affixes in the name parsing logic. Eg see Wikipedia: https://en.m.wikipedia.org/wiki/List_of_family_name_affixes

---

Erick Peirson
Postdoctoral Scholar
ASU-SFI Center for Biosocial Complexity
Arizona State University

**Comment by yzou20** [comment]
Thanks for the info. I will think about that!
