### ISSUE TITLE
utilities.handle_attribs() sets all dates (other attributes?) to a single value

### ISSUE THREAD

**Issue by erickpeirson** [diging/tethne#9]
This dataset has papers from 1999-2013

```
>>> dates_meta = {}
>>> for node in meta_list:
...    if node['date'] not in dates_meta.keys(): dates_meta[node['date']] = 1
...    else: dates_meta[node['date']] += 1
>>> dates_meta.keys()
[1999,
 2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013]
```

But if I run biblio_coupling, and then pull out the nodes, all nodes have date=1999:

```
>>> dates = {}
>>> for node in bc_nodes:
...     if node[1]['date'] not in dates.keys(): dates[node[1]['date']] = 1
...     else: dates[node[1]['date']] += 1
>>> dates.keys()
[1999]
```

Seems to do the same thing with titles.

**Comment by aabaker99** [comment]
I don't quite follow the code snippets; are you leaving out some of the code?

Is this only happening in biblio_coupilng? I don't think this would be cause by the utility function, but I'm already in the process of changing that function. If it does only occur for biblio_coupling I found and corrected a typo in the code that could be responsible.
